kind: pipeline
type: docker
name: default

steps:
- name: composer install
  image: composer
  commands:
  - echo '開始安裝 composer'
  - composer install

- name: Unit test
  image: php
  commands:
  - echo '開始單元測試'
  - echo 'php artisan test'

- name: test1
  image: docker:dind
  commands:
  - docker run --help

build:
    image: node:6.10.0
    commands:
      - yarn install
      - yarn test

- name: test2
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker info
  volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
