kind: pipeline
type: docker
name: default

steps:
- name: composer install
  image: composer
  commands:
  - echo '開始安裝 composer'
  - composer install

- name: Unit test
  image: php
  commands:
  - echo '開始單元測試'
  - echo 'php artisan test'

- name: test1
  image: docker
  commands:
  - docker run --help

- name: build
  image: docker
  commands:
  - sleep 5
  - docker --help
  - docker ps
  - docker build -t hello-world .
