kind: pipeline
type: docker
name: default

steps:
- name: composer install
  image: composer
  commands:
  - echo '開始安裝 composer'
  - composer install

- name: Unit test
  image: php
  commands:
  - echo '開始單元測試'
  - echo 'php artisan test'

- name: (test)build image
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/lib
  commands:
  - docker ps -a
