kind: pipeline
type: docker
name: default

steps:
- name: composer install
  image: composer
  commands:
  - echo '開始安裝 composer'
  - composer install

- name: Unit test
  image: php
  commands:
  - echo '開始單元測試'
  - echo 'php artisan test'

- name: test
  image: docker:dind
  volumes:
  - name: dockersock
  commands:
  - sleep 3 # give docker enough time to start
  - docker ps -a
