kind: pipeline
type: docker
name: default

steps:
- name: composer install
  image: composer
  commands:
  - echo '開始安裝 composer'
  - composer install

- name: Unit test
  image: php
  commands:
  - echo '開始單元測試'
  - echo 'php artisan test'

- name: dockerhub build & push image
  image: plugins/docker
  settings:
    username: mic121key
    password: Elk1306!@
    repo: mic121key/autobuild
    tags: latest

