kind: pipeline
type: docker
name: default

steps:
- name: composer install
  image: composer
  commands:
  - echo '開始安裝 composer'
  - composer install

- name: Unit test
  image: php
  commands:
  - echo '開始單元測試'
  - echo 'php artisan test'

- name: test1
  image: docker:dind
  commands:
  - docker run --help

- name: build
  image: docker:17.05.0-ce-dind
  environment:
    - DOCKER_HOST=tcp://docker:2375
  commands:
    - sleep 5
    - docker ps
    - docker build -t hello-world .
