kind: pipeline
name: default

steps:
- name: composer install
  image: composer
  commands:
  - echo '開始安裝 composer'
  - composer install

- name: test
  image: php:7
  commands:
  - echo '11111'
  - echo '456777'
